Deploy
3dartix/notification pull request #38
Opened 2020-12-06 20:56 UTC by mzub

2020-12-06 21:01 UTC, mzub commented
Поправил общий код, теперь можно выкладывать сразу на heroku не модифицируя код (актуально для rest, parser, notification сервисов)
Немного еще оптимизировал, в т.ч. и в avito но он по прежнему не готов конечно

2020-12-12 12:00 UTC, 3dartix requested changes

2020-12-12 12:00 UTC, 3dartix commented on nb-configuration.xml
> +<?xml version="1.0" encoding="UTF-8"?>
если не нужен, то давай исключим

2020-12-12 12:00 UTC, 3dartix commented on notification-service/src/main/java/ru/geekbrains/notification/telegram/TelegramBot.java
> +            user.getAnswer().setFloor("");
а это зачем тут?

2020-12-12 12:00 UTC, 3dartix commented on parser-service/nb-configuration.xml
> +<?xml version="1.0" encoding="UTF-8"?>
тоже давай уберем

2020-12-12 12:00 UTC, 3dartix commented on parser-service/src/test/java/ru/geekbrains/requesthandler/RequestHndlerTest.java
> +//        taskService.poll();
замени аннотацией @ignore

2020-12-12 12:00 UTC, 3dartix commented on rest-service/nbactions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
а это что?

2023-05-09 13:22 UTC, closed without merging